### ISSUE TITLE
All the arguments rely on ancient, mostly discredited ideas about root cause

### ISSUE THREAD

**Issue by ibillwilson** [adaptivecapacitylabs/CritiquesOnRootCause#9]
No serious, modern practitioner of root cause analysis believes that:

- every event has a single root cause;
- that a linear sequence of events is a sufficient event description;
- that systems are always easy to understand;
- that 5 whys is an adequate technique suitable for anything other than "toy" events;
- that all human actions are failures;
- that all future events will occur in the same fashion as the one being investigated.

Modern root cause analysis is systems-based, acknowledges probabilistic influences and feedback loops, and embraces the view that "human performance" is not always negative. In the nuclear power industry, for instance, any root cause analysis that proposed a single, simple root cause would probably be laughed out of the room.

**Comment by jallspaw** [comment]
I agree with your sentiment here. While your comment has some strong "[No True Scotsman](https://en.wikipedia.org/wiki/No_true_Scotsman)" vibes (and sweeps together a number of topics related to the term), faulty perspectives like these continue to be alive and well in many domains. 

There is still much progress to be made (especially in the tech industry) to match/catch-up to what you've posed here.
